CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    type TEXT NOT NULL DEFAULT 'Saída',
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'Outros',
    subcategory TEXT NOT NULL DEFAULT '',
    purpose TEXT NOT NULL DEFAULT 'Registrado pelo Nexus Finance',
    classification TEXT NOT NULL DEFAULT 'Controlável',
    amount NUMERIC(14, 2) NOT NULL CHECK (amount >= 0),
    status TEXT NOT NULL DEFAULT 'Realizado',
    note TEXT NOT NULL DEFAULT '',
    mode TEXT NOT NULL DEFAULT 'Movimentação',
    installments INTEGER NOT NULL DEFAULT 0 CHECK (installments >= 0),
    current_installment INTEGER NOT NULL DEFAULT 0 CHECK (current_installment >= 0),
    due_day INTEGER NOT NULL DEFAULT 0 CHECK (due_day BETWEEN 0 AND 31),
    recurrence TEXT NOT NULL DEFAULT 'Único',
    priority TEXT NOT NULL DEFAULT '',
    paid_at DATE
);

CREATE INDEX IF NOT EXISTS transactions_date_id_idx ON transactions (date DESC, id DESC);

CREATE TABLE IF NOT EXISTS goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    target NUMERIC(14, 2) NOT NULL CHECK (target > 0),
    current NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (current >= 0),
    date DATE
);
